spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/jxtelecom?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        #连接池的配置信息
        initialSize: 50
        minIdle: 50
        maxActive: 500
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        removeAbandonedTimeout: 180000
        removeAbandoned: true

        # Druid 配置
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    redis:
        host: 127.0.0.1
        port: 6379
        pool:
            max-active: 10000
            max-wait: 60000
            max-idle: 100
            timeout: 60000
